### ISSUE TITLE
run the results of load_features.py

### ISSUE THREAD

**Issue by CelineZhou03** [cameronfabbri/Compute-Features#1]
when I run the load_features.py but only one test4 image is output.

**Comment by cameronfabbri** [comment]
Yeah it's just an example script for how you should load the features when using this in your application.

**Comment by CelineZhou03** [comment]
Can features only be saved as.pkl files?
I tried to save as.txt or.scv, but the saved files were opened with the messy code.
I want to save the feature in TXT format and save one line per image. How do I change it?

**Comment by CelineZhou03** [comment]
Can features only be saved as.pkl files?
I tried to save as.txt or.scv, but the saved files were opened with a messy code.
I want to save the feature in TXT format and save one line per image. How do I change it?
